name = "roll-dorado-casino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.pt"
HMAC_KEY = "e7fb9e7b6780ca8b3988b15247a5b03aeba6f143af1f02468a562b89a3746e57"
COOKIE_NAME = "kla"
PLAY_PATH = "begin"
BUTTON_ID = "pcd9f512e6bc0f8cbe514b590473ba1e8"
GATE_SALT = "59f6e30c47902b5e"
